plan_task:
  description: |
    1. Prioritize the latest trends, key players, and noteworthy news on {topic}.
    2. Identify the target audience, considering their interests and pain points.
    3. Develop a detailed content outline including an introduction, key points, and a call to action.
    4. Include SEO keywords and relevant data or sources.
  expected_output: A comprehensive content plan document with an outline, audience analysis, SEO keywords, and resources.
  agent: planner

write_task:
  description: |
    1. Use the content plan to craft a compelling blog post on {topic}.
    2. Incorporate SEO keywords naturally.
    3. Sections/Subtitles are properly named in an engaging manner.
    4. Ensure the post is structured with an engaging introduction, insightful body, and a summarizing conclusion.
    5. Format proper headings, paragraphs, and styling.
    6. Proofread for grammatical errors and alignment with the brand's voice.
  expected_output: A beautifully formatted markdown document with proper structure, spaces, citations, and view elements that enhance readability and presentation, without markdown code blocks (no ``` markers).
  agent: writer
  depends_on:
    - plan_task

edit_task:
  description: Proofread the given blog post for grammatical errors and alignment with the brand's voice
  expected_output: >
    A beautifully formatted markdown document with proper structure, spaces, citations, and view elements that enhance readability and presentation, without markdown code blocks (no ``` markers).
  agent: editor
  depends_on:
    - write_task

format_task:
  description: |
    Format the executive report into a beautiful markdown document following these guidelines:
    1. Use proper markdown headers (#, ##, ###)
    2. Format key findings and insights as bullet points
    3. Add proper spacing and sections breaks
    4. Make recommendations stand out using blockquotes
    5. Ensure the date is properly formatted
    6. Add a table of contents at the beginning
    7. Use horizontal rules (---) to separate major sections
    8. Add inline citations for each major claim using (Author, Year) format
    9. Include a Sources section at the end
    10. Each source should include title, publisher/author, and URL
    11. Link inline citations to the corresponding entry in the Sources section
    12. make sure it should not contain markdown code blocks (no ``` markers)
  expected_output: A beautifully formatted markdown document that follows all the specified guidelines, enhancing readability and presentation.
  agent: formatter
  depends_on:
    - edit_task

design_task:
  description: >
    Create a banner image for the blog post that captures the essence of the content and attracts
    readers' attention
  expected_output: A visually appealing banner image related to the blog post topic
  agent: designer
  depends_on:
    - write_task
