plan_task:
  description: |
    1. Prioritize the latest trends, key players, and noteworthy news on {topic}.
    2. Identify the target audience, considering their interests and pain points.
    3. Develop a detailed content outline including an introduction, key points, and a call to action.
    4. Include SEO keywords and relevant data or sources.
  expected_output: A comprehensive content plan document with an outline, audience analysis, SEO keywords, and resources.
  agent: planner

write_task:
  description: |
    1. Use the content plan to craft a compelling blog post on {topic}.
    2. Incorporate SEO keywords naturally.
    3. Sections/Subtitles are properly named in an engaging manner.
    4. Ensure the post is structured with an engaging introduction, insightful body, and a summarizing conclusion.
    5. Format proper headings, paragraphs, and styling.
    6. Proofread for grammatical errors and alignment with the brand's voice.
  expected_output: A well-written blog post in Markdown format, ready for publication, each section should have 2 or 3 paragraphs.
  agent: writer
  depends_on:
    - plan_task

edit_task:
  description: Proofread the given blog post for grammatical errors and alignment with the brand's voice
  expected_output: >
    A well-written blog post, ready for publication, each section should have 2 or 3 paragraphs.
  agent: editor
  depends_on:
    - write_task

design_task:
  description: >
    Create a banner image for the blog post that captures the essence of the content and attracts
    readers' attention
  expected_output: A visually appealing banner image related to the blog post topic
  agent: designer
  depends_on:
    - write_task

