import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import bloggptLogo from "./assets/bloggpt logo.png";
import BlogListing from "@/components/BlogListing";
import Link from "next/link"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="absolute top-4 left-4 z-50">
          <Link href="/">
            <Image src={bloggptLogo} alt="bloggpt logo" />
          </Link>
        </div>
        <div className="container">
          <div className="left-container">{children}</div>
          <div className="right-container">
            <BlogListing />
          </div>
        </div>
      </body>
    </html>
  );
}
